name: dmtools_styleguide
description: Flutter implementation of DMTools design system components and style guidelines
version: 0.1.0
homepage: https://github.com/yourusername/dmtools-flutter

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  url_launcher: ^6.3.1
  go_router: ^16.0.0
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  collection: ^1.17.2
  flutter_markdown: ^0.7.4+1
  markdown: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  alchemist: ^0.12.1
  flutter_launcher_icons: ^0.14.4
  flutter_web_plugins:
    sdk: flutter

# We need to manually copy the icon file to web/favicon.png
# flutter_launcher_icons:
#   web:
#     generate: true
#     image_path: "assets/img/dmtools-icon.svg"
#     background_color: "#FFFFFF"
#     theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600